version: '3.8'

services:
  floor-plan-parser:
    build: .
    tty: true
    stdin_open: true
    container_name: floor-plan-parser
    volumes:
      - ./testcases:/app/testcases
      - ./output:/app/output
